### ISSUE TITLE
"prepareDataFunction" doesn't works. 

### ISSUE THREAD

**Issue by rajgodia** [webdatarocksteam/pivot-google-charts-angular#2]
I used below code in order to use **prepareDataFunction** for making changes before sending data to Graph.
Can you please help, since I am just returning the data as it is without any change, still it doesn't work.

```
prepareDataFunction: (rawData: any) => {
          console.log(rawData);
          return rawData;
        }
```

**Comment by iansadovy** [comment]
Hello @rajgodia,

Thank you for the question.
Please note that when you are using `prepareDataFunction` it means that this function should transform data from WDR format to Google Charts format. So, when you return data without any change, it cannot be understood by Google Charts.

Regards,
Ian
